### ISSUE TITLE
Error When Installing node-red using npm

### ISSUE THREAD

**Issue by rahmatullah5** [guidone/node-red-contrib-chatbot#112]
when i try to install Redbot http://red-bot.io/ ,i execute the first line of their instalation code for installing node-red `sudo npm install -g node-red` ,but i getting this errors

    
    npm WARN deprecated nodemailer@1.11.0: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
    npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
    /usr/local/bin/node-red -> /usr/local/lib/node_modules/node-red/red.js
    /usr/local/bin/node-red-pi -> /usr/local/lib/node_modules/node-red/bin/node-red-pi
    
    > bcrypt@1.0.3 install /usr/local/lib/node_modules/node-red/node_modules/bcrypt
    > node-pre-gyp install --fallback-to-build
    
    node-pre-gyp ERR! Tried to download(undefined): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v57-darwin-x64.tar.gz
    node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@8.2.1 (node-v57 ABI) (falling back to source compile with node-gyp)
    gyp ERR! configure error
    gyp ERR! stack Error: Command failed: /Users/fourtyonestudio/.pyenv/shims/python2 -c import platform; print(platform.python_version());
    gyp ERR! stack pyenv: python2: command not found
    gyp ERR! stack
    gyp ERR! stack The `python2' command exists in these Python versions:
    gyp ERR! stack   2.7.8
    gyp ERR! stack
    gyp ERR! stack
    gyp ERR! stack     at ChildProcess.exithandler (child_process.js:270:12)
    gyp ERR! stack     at emitTwo (events.js:125:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
    gyp ERR! stack     at maybeClose (internal/child_process.js:921:16)
    gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:348:11)
    gyp ERR! stack     at emitOne (events.js:115:13)
    gyp ERR! stack     at Socket.emit (events.js:210:7)
    gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:549:12)
    gyp ERR! System Darwin 16.6.0
    gyp ERR! command "/usr/local/Cellar/node/8.2.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/node-red/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/usr/local/lib/node_modules/node-red/node_modules/bcrypt/lib/binding"
    gyp ERR! cwd /usr/local/lib/node_modules/node-red/node_modules/bcrypt
    gyp ERR! node -v v8.2.1
    gyp ERR! node-gyp -v v3.6.2
    gyp ERR! not ok
    node-pre-gyp ERR! build error
    node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/8.2.1/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/node-red/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/usr/local/lib/node_modules/node-red/node_modules/bcrypt/lib/binding' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/node-red/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
    node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
    node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:921:16)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
    node-pre-gyp ERR! System Darwin 16.6.0
    node-pre-gyp ERR! command "/usr/local/Cellar/node/8.2.1/bin/node" "/usr/local/lib/node_modules/node-red/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
    node-pre-gyp ERR! cwd /usr/local/lib/node_modules/node-red/node_modules/bcrypt
    node-pre-gyp ERR! node -v v8.2.1
    node-pre-gyp ERR! node-pre-gyp -v v0.6.36
    node-pre-gyp ERR! not ok
    Failed to execute '/usr/local/Cellar/node/8.2.1/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/node-red/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/usr/local/lib/node_modules/node-red/node_modules/bcrypt/lib/binding' (1)
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bcrypt@1.0.3 (node_modules/node-red/node_modules/bcrypt):
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bcrypt@1.0.3 install: `node-pre-gyp install --fallback-to-build`
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
    
    + node-red@0.17.5

Can someone give me an advice about erros above ?

Thanks

**Comment by rahmatullah5** [comment]
Forget to add `--unsafe-perm`

**Comment by parthsharma1996** [comment]
I am having a similar error. However adding `--unsafe-perm` doesn't resolve it.

Can someone help me figure out what's happening?

Here's the entire output
```
(rasa_env) ❯ npm install i -g --unsafe-perm node-red
npm WARN deprecated bcrypt@1.0.3: bcrypt < v2.0.0 is susceptible to bcrypt wrap-around bug. Upgrade to bcrypt >= v2.0.0 for improved support for newer bcrypt hashes
npm WARN deprecated i18next-client@1.10.3: you can use npm install i18next from version 2.0.0
npm WARN deprecated mailparser@0.6.2: This project is unmaintained
npm WARN deprecated nodemailer@1.11.0: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated mimelib@0.3.1: This project is unmaintained
npm WARN deprecated mailcomposer@2.1.0: This project is unmaintained
npm WARN deprecated buildmail@2.0.0: This project is unmaintained
/home/parth/.nvm/versions/node/v10.2.1/bin/node-red-pi -> /home/parth/.nvm/versions/node/v10.2.1/lib/node_modules/node-red/bin/node-red-pi
/home/parth/.nvm/versions/node/v10.2.1/bin/node-red -> /home/parth/.nvm/versions/node/v10.2.1/lib/node_modules/node-red/red.js

> bcrypt@1.0.3 install /home/parth/.nvm/versions/node/v10.2.1/lib/node_modules/node-red/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@10.2.1 (node-v64 ABI) (falling back to source compile with node-gyp) 
make: Entering directory '/home/parth/.nvm/versions/node/v10.2.1/lib/node_modules/node-red/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
../src/bcrypt.cc: In function ‘void encode_salt(char*, u_int8_t*, u_int16_t, u_int8_t)’:
../src/bcrypt.cc:132:1: warning: ‘snprintf’ output may be truncated before the last format character [-Wformat-truncation=]
 encode_salt(char *salt, u_int8_t *csalt, u_int16_t clen, u_int8_t logr)
 ^~~~~~~~~~~
../src/bcrypt.cc:139:10: note: ‘snprintf’ output between 4 and 5 bytes into a destination of size 4
  snprintf(salt + 4, 4, "%2.2u$", logr);
  ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/bcrypt.cc: In function ‘void bcrypt(const char*, const char*, char*)’:
../src/bcrypt.cc:165:1: warning: ‘snprintf’ output may be truncated before the last format character [-Wformat-truncation=]
 bcrypt(const char *key, const char *salt, char *encrypted)
 ^~~~~~
../src/bcrypt.cc:270:10: note: ‘snprintf’ output between 4 and 5 bytes into a destination of size 4
  snprintf(encrypted + i, 4, "%2.2u$", logr);
  ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
In file included from ../../nan/nan.h:192:0,
                 from ../src/bcrypt_node.cc:1:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:112:15: error: ‘class v8::Object’ has no member named  ForceSet’
   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
               ^~~~~~~~
In file included from ../src/bcrypt_node.cc:1:0:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:835:60: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, func, argc, argv);
                                                            ^
In file included from ../../nan/nan.h:49:0,
                 from ../src/bcrypt_node.cc:1:
/home/parth/.node-gyp/10.2.1/include/node/node.h:172:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/parth/.node-gyp/10.2.1/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../src/bcrypt_node.cc:1:0:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:850:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, symbol, argc, argv);
                                                              ^
In file included from ../../nan/nan.h:49:0,
                 from ../src/bcrypt_node.cc:1:
/home/parth/.node-gyp/10.2.1/include/node/node.h:165:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/parth/.node-gyp/10.2.1/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../src/bcrypt_node.cc:1:0:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:865:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, method, argc, argv);
                                                              ^
In file included from ../../nan/nan.h:49:0,
                 from ../src/bcrypt_node.cc:1:
/home/parth/.node-gyp/10.2.1/include/node/node.h:158:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/parth/.node-gyp/10.2.1/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../src/bcrypt_node.cc:1:0:
../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const’:
../../nan/nan.h:1479:5: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
     ));
     ^
In file included from ../../nan/nan.h:49:0,
                 from ../src/bcrypt_node.cc:1:
/home/parth/.node-gyp/10.2.1/include/node/node.h:172:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/parth/.node-gyp/10.2.1/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
node-pre-gyp ERR! Tried to download(undefined): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@10.2.1 (node-v64 ABI) (falling back to source compile with node-gyp) 
make: *** [bcrypt_lib.target.mk:97: Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
make: Leaving directory '/home/parth/.nvm/versions/node/v10.2.1/lib/node_modules/node-red/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/parth/.nvm/versions/node/v10.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.12.8-2-ARCH
gyp ERR! command "/home/parth/.nvm/versions/node/v10.2.1/bin/node" "/home/parth/.nvm/versions/node/v10.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/parth/.nvm/versions/node/v10.2.1/lib/node_modules/node-red/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/home/parth/.nvm/versions/node/v10.2.1/lib/node_modules/node-red/node_modules/bcrypt/lib/binding"
gyp ERR! cwd /home/parth/.nvm/versions/node/v10.2.1/lib/node_modules/node-red/node_modules/bcrypt
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/parth/.nvm/versions/node/v10.2.1/bin/node /home/parth/.nvm/versions/node/v10.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/parth/.nvm/versions/node/v10.2.1/lib/node_modules/node-red/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/parth/.nvm/versions/node/v10.2.1/lib/node_modules/node-red/node_modules/bcrypt/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/parth/.nvm/versions/node/v10.2.1/lib/node_modules/node-red/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Linux 4.12.8-2-ARCH
node-pre-gyp ERR! command "/home/parth/.nvm/versions/node/v10.2.1/bin/node" "/home/parth/.nvm/versions/node/v10.2.1/lib/node_modules/node-red/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/parth/.nvm/versions/node/v10.2.1/lib/node_modules/node-red/node_modules/bcrypt
node-pre-gyp ERR! node -v v10.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
Failed to execute '/home/parth/.nvm/versions/node/v10.2.1/bin/node /home/parth/.nvm/versions/node/v10.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/parth/.nvm/versions/node/v10.2.1/lib/node_modules/node-red/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/parth/.nvm/versions/node/v10.2.1/lib/node_modules/node-red/node_modules/bcrypt/lib/binding' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bcrypt@1.0.3 (node_modules/node-red/node_modules/bcrypt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bcrypt@1.0.3 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ node-red@0.18.7
+ i@0.3.6
added 1 package and updated 1 package in 5.081s

```
