### ISSUE TITLE
Unhandled rejection TypeError

### ISSUE THREAD

**Issue by metabaron** [guidone/node-red-contrib-chatbot#122]
Unhandled rejection TypeError: Cannot read property 'set' of undefined
    at messageOk (/Users/mathieufeulvarch/.node-red/node_modules/node-red-contrib-chatbot/nodes/chatbot-telegram-receive.js:420:20)
    at tryCatcher (/Users/mathieufeulvarch/.node-red/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/mathieufeulvarch/.node-red/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/mathieufeulvarch/.node-red/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/mathieufeulvarch/.node-red/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/mathieufeulvarch/.node-red/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/mathieufeulvarch/.node-red/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/mathieufeulvarch/.node-red/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/mathieufeulvarch/.node-red/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)

When: Every 5 minutes, I pull messages from a MySQL database (yes, I'm sure the results are not empty) and forward a message with the results to a Telegram channel.

Let me know what / if you want me to test.

**Comment by guidone** [comment]
@metabaron Sorry for the late answer. Fixed in `0.8.7`, it appears the chatContext is not present when the error is raised, this is strange, let me know if there are other errors
