### ISSUE TITLE
Telegram receiver does not work

### ISSUE THREAD

**Issue by unnikked** [guidone/node-red-contrib-chatbot#18]
I'm using an instance on openshift. 

Node 0.10
node-red-contrib-chatbot 0.5.13

```
Unhandled rejection ReferenceError: Promise is not defined
    at TelegramBotNode.getMessageDetails (/var/lib/openshift/57e00ddb2d527132ed0000ed/app-root/runtime/repo/node_modules/node-red-contrib-chatbot/chatbot-telegram-receive.js:39:18)
    at TelegramBotNode.handleMessage (/var/lib/openshift/57e00ddb2d527132ed0000ed/app-root/runtime/repo/node_modules/node-red-contrib-chatbot/chatbot-telegram-receive.js:177:12)
    at TelegramBot.emit (/var/lib/openshift/57e00ddb2d527132ed0000ed/app-root/runtime/repo/node_modules/node-red-contrib-chatbot/node_modules/node-telegram-bot-api/node_modules/eventemitter3/index.js:116:35)
    at TelegramBot.processUpdate (/var/lib/openshift/57e00ddb2d527132ed0000ed/app-root/runtime/repo/node_modules/node-red-contrib-chatbot/node_modules/node-telegram-bot-api/lib/telegram.js:104:14)
    at /var/lib/openshift/57e00ddb2d527132ed0000ed/app-root/runtime/repo/node_modules/node-red-contrib-chatbot/node_modules/node-telegram-bot-api/lib/telegramPolling.js:52:17
    at Array.forEach (native)
    at /var/lib/openshift/57e00ddb2d527132ed0000ed/app-root/runtime/repo/node_modules/node-red-contrib-chatbot/node_modules/node-telegram-bot-api/lib/telegramPolling.js:49:17
    at tryCatcher (/var/lib/openshift/57e00ddb2d527132ed0000ed/app-root/runtime/repo/node_modules/node-red-contrib-chatbot/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/var/lib/openshift/57e00ddb2d527132ed0000ed/app-root/runtime/repo/node_modules/node-red-contrib-chatbot/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/var/lib/openshift/57e00ddb2d527132ed0000ed/app-root/runtime/repo/node_modules/node-red-contrib-chatbot/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/var/lib/openshift/57e00ddb2d527132ed0000ed/app-root/runtime/repo/node_modules/node-red-contrib-chatbot/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/var/lib/openshift/57e00ddb2d527132ed0000ed/app-root/runtime/repo/node_modules/node-red-contrib-chatbot/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/var/lib/openshift/57e00ddb2d527132ed0000ed/app-root/runtime/repo/node_modules/node-red-contrib-chatbot/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/var/lib/openshift/57e00ddb2d527132ed0000ed/app-root/runtime/repo/node_modules/node-red-contrib-chatbot/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:442:13)
```

**Comment by guidone** [comment]
@unnikked I think that that node version doesn't support Promises, is the upgrade possible?

Otherwise I can try with a polyfill
