### ISSUE TITLE
Error with telegram bot

### ISSUE THREAD

**Issue by TotallyInformation** [guidone/node-red-contrib-chatbot#181]
```
0|red      | { Error: ETELEGRAM: 409 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
0|red      |     at request.then.resp (C:\Users\julia\.node-red\node_modules\node-telegram-bot-api\src\telegram.js:213:15)
0|red      | From previous event:
0|red      |     at Request.RP$exposed [as then] (C:\Users\julia\.node-red\node_modules\request-promise-core\lib\plumbing.js:145:61)
0|red      |     at TelegramBot._request (C:\Users\julia\.node-red\node_modules\node-telegram-bot-api\src\telegram.js:201:8)
0|red      |     at TelegramBot.getUpdates (C:\Users\julia\.node-red\node_modules\node-telegram-bot-api\src\telegram.js:470:17)
0|red      |     at _unsetWebHook.then (C:\Users\julia\.node-red\node_modules\node-telegram-bot-api\src\telegramPolling.js:140:29)
0|red      | From previous event:
0|red      |     at bot.getUpdates.catch.err (C:\Users\julia\.node-red\node_modules\node-telegram-bot-api\src\telegramPolling.js:139:39)
0|red      |     at runCallback (timers.js:789:20)
0|red      |     at tryOnImmediate (timers.js:751:5)
0|red      |     at processImmediate [as _immediateCallback] (timers.js:722:5)
0|red      | From previous event:
0|red      |     at TelegramBotPolling._getUpdates (C:\Users\julia\.node-red\node_modules\node-telegram-bot-api\src\telegramPolling.js:137:13)
0|red      |     at TelegramBotPolling._polling (C:\Users\julia\.node-red\node_modules\node-telegram-bot-api\src\telegramPolling.js:89:8)
0|red      |     at Timeout._pollingTimeout.setTimeout [as _onTimeout] (C:\Users\julia\.node-red\node_modules\node-telegram-bot-api\src\telegramPolling.js:114:56)
0|red      |     at ontimeout (timers.js:475:11)
0|red      |     at tryOnTimeout (timers.js:310:5)
0|red      |     at Timer.listOnTimeout (timers.js:270:5)
0|red      |   code: 'ETELEGRAM',
0|red      |   response:
... lots of detailed output ...
0|red      |      body:
0|red      |       { ok: false,
0|red      |         error_code: 409,
0|red      |         description: 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running' } } }
```
I am also getting
```
0|red      | 2 Mar 21:59:31 - [warn] Missing node modules:                                                    
0|red      | 2 Mar 21:59:31 - [warn]  - node-red-contrib-chatbot (0.9.24): chatbot-apiai-token, chatbot-apiai 
```
Running on node.js v8.9.4, Node-RED v0.18.4 on Windows 10. redbot v 0.9.24

The bot it refers to is not being referenced anywhere else.

**Comment by guidone** [comment]
Can you try opening the `Configuration nodes` menu item and see if there's some hidden Telegram config node that may be run another Telegram instance
