### ISSUE TITLE
Unhandled exceptions with telegrambot

### ISSUE THREAD

**Issue by mrummuka** [guidone/node-red-contrib-chatbot#21]
For a while telegram receiver/sender works without issues in a node-red chat flow. However after node-red has been running for some time ( ~few days? (to-be-measured)) quite a few of these begin to occur.

```
Unhandled rejection TimeoutError: operation timed out
    at afterTimeout (/usr/local/lib/node_modules/node-red-contrib-chatbot/node_modules/request-promise/node_modules/bluebird/js/main/timers.js:16:15)
    at timeoutTimeout (/usr/local/lib/node_modules/node-red-contrib-chatbot/node_modules/request-promise/node_modules/bluebird/js/main/timers.js:59:9)
    at Timer.listOnTimeout (timers.js:92:15)

```

Any ideas what might be causing them?

**Comment by guidone** [comment]
@mrummuka yes, it's an un-handled exception of the telegram library.  I was not able to have it fixed by the author, I think I'm going to fork the lib

**Comment by mrummuka** [comment]
OK, thanks for the information. Hopefully you'll get it fixed - I really liked your  simple approach with node-red-contrib-chatbot
