### ISSUE TITLE
Telegram Bot Configuration Problems

### ISSUE THREAD

**Issue by sriramsv** [guidone/node-red-contrib-chatbot#288]
Node Red Version: 0.19.5
Red Bot Version: ~0.16.3

```
13 Feb 22:15:24 - [error] [chatbot-telegram-node:aa0de725.99e168] TypeError: Cannot read property 'get' of undefined


    at new TelegramBotNode (/data/node_modules/node-red-contrib-chatbot/nodes/chatbot-telegram-receive.js:35:62)


    at createNode (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/flows/Flow.js:305:18)


    at Flow.start (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/flows/Flow.js:67:31)


    at start (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/flows/index.js:328:29)


    at /usr/src/node-red/node_modules/node-red/red/runtime/nodes/flows/index.js:164:25


    at <anonymous>


    at process._tickCallback (internal/process/next_tick.js:189:7)


13 Feb 22:15:24 - [info] Started modified nodes


13 Feb 22:15:27 - [error] [chatbot-conversation:e105f922.6f0fa8] Chatbot not found or not configured properly```

**Comment by sriramsv** [comment]
```[
    {
        "id": "3527aec1.bc5e02",
        "type": "chatbot-telegram-receive",
        "z": "81926c5e.a3fd4",
        "bot": "aa0de725.99e168",
        "botProduction": "aa0de725.99e168",
        "x": 160,
        "y": 320,
        "wires": [
            [
                "8acb902e.403f"
            ]
        ]
    },
    {
        "id": "b25aea4b.9b6d88",
        "type": "chatbot-telegram-send",
        "z": "81926c5e.a3fd4",
        "bot": "aa0de725.99e168",
        "botProduction": "aa0de725.99e168",
        "track": false,
        "passThrough": false,
        "outputs": 0,
        "x": 630,
        "y": 320,
        "wires": []
    },
    {
        "id": "8acb902e.403f",
        "type": "chatbot-message",
        "z": "81926c5e.a3fd4",
        "name": "",
        "message": [
            {
                "message": "Hello"
            }
        ],
        "answer": false,
        "silent": false,
        "x": 390,
        "y": 320,
        "wires": [
            [
                "b25aea4b.9b6d88"
            ]
        ]
    },
    {
        "id": "aa0de725.99e168",
        "type": "chatbot-telegram-node",
        "z": "",
        "botname": "bot",
        "usernames": "467067128",
        "providerToken": "",
        "polling": "1000",
        "store": "",
        "log": "",
        "parseMode": "",
        "debug": false
    }
]```

**Comment by guidone** [comment]
This is strange, the error is near `RED.settings.functionGlobalContext` which is a core function of Node-RED.

Can you verify that in your settings.js file of Node-RED there's something in the key `functionGlobalContext`?

**Comment by sriramsv** [comment]
I commented out whatever was there in my functionGlobalContext, and tried again.

I am still getting the following error:
```

17 Feb 12:23:00 - [error] [chatbot-telegram-node:f44aeec.88a351] TypeError: Cannot read property 'get' of undefined


    at new TelegramBotNode (/data/node_modules/node-red-contrib-chatbot/nodes/chatbot-telegram-receive.js:35:62)


    at createNode (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/flows/Flow.js:305:18)


    at Flow.start (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/flows/Flow.js:67:31)


    at start (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/flows/index.js:328:29)


    at /usr/src/node-red/node_modules/node-red/red/runtime/nodes/flows/index.js:164:25


    at <anonymous>


    at process._tickCallback (internal/process/next_tick.js:189:7)


17 Feb 12:23:00 - [warn] [chatbot-telegram-receive:1ba018a1.997d97] Missing configuration in Telegram Receiver

```

**Comment by sriramsv** [comment]
Ok, i was able to get rid of the issue after replacing the settings.js to a default one. I dont know what config caused the issue though.
