### ISSUE TITLE
Unhandled rejection Error continuously showing up 

### ISSUE THREAD

**Issue by jmikerq** [guidone/node-red-contrib-chatbot#3]
I was testing all the chatbot nodes in this chatbot contrib, when deploying these chatbot nodes in node-red, whenever I start the flow, an error message would keep showing on the console.

10 Aug 22:55:51 - [info] Stopping flows
10 Aug 22:55:51 - [info] Stopped flows
10 Aug 22:55:51 - [info] Starting flows
10 Aug 22:55:51 - [info] Started flows
Unhandled rejection Error: Closing node.
    at Object.ensureErrorObject (/home/vagrant/.node-red/node_modules/node-red-contrib-chatbot/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/util.js:261:20)
    at Promise._rejectCallback (/home/vagrant/.node-red/node_modules/node-red-contrib-chatbot/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:469:22)
    at Promise._settlePromiseFromHandler (/home/vagrant/.node-red/node_modules/node-red-contrib-chatbot/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:513:17)
    at Promise._settlePromiseAt (/home/vagrant/.node-red/node_modules/node-red-contrib-chatbot/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/home/vagrant/.node-red/node_modules/node-red-contrib-chatbot/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/vagrant/.node-red/node_modules/node-red-contrib-chatbot/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/vagrant/.node-red/node_modules/node-red-contrib-chatbot/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/vagrant/.node-red/node_modules/node-red-contrib-chatbot/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

Although the error messages mention about the telegram-bot-api, but I found that, whether or not I have telegram nodes set up in the flow, the same messages would come up.

**Comment by guidone** [comment]
Thanks @jmikerq I'll look into it

**Comment by guidone** [comment]
FIxed in #5
