### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot assign to read only property 'writeQueueSize' of object '#<TCP>'

### ISSUE THREAD

**Issue by ghost** [guidone/node-red-contrib-chatbot#317]
Whenever I use anything that manipulates an incoming Discord message, I get the following error:

```
Jun 29 21:52:48 nodered sudo[25427]: (node:25428) UnhandledPromiseRejectionWarning: TypeError: Cannot assign to read only property 'writeQueueSize' of object '#<TCP>'
Jun 29 21:52:48 nodered sudo[25427]:     at _clone (/usr/local/lib/node_modules/node-red/node_modules/clone/clone.js:162:16)
Jun 29 21:52:48 nodered sudo[25427]:     at _clone (/usr/local/lib/node_modules/node-red/node_modules/clone/clone.js:162:18)
Jun 29 21:52:48 nodered sudo[25427]:     at _clone (/usr/local/lib/node_modules/node-red/node_modules/clone/clone.js:162:18)
Jun 29 21:52:48 nodered sudo[25427]:     at _clone (/usr/local/lib/node_modules/node-red/node_modules/clone/clone.js:162:18)
Jun 29 21:52:48 nodered sudo[25427]:     at _clone (/usr/local/lib/node_modules/node-red/node_modules/clone/clone.js:162:18)
Jun 29 21:52:48 nodered sudo[25427]:     at _clone (/usr/local/lib/node_modules/node-red/node_modules/clone/clone.js:162:18)
Jun 29 21:52:48 nodered sudo[25427]:     at _clone (/usr/local/lib/node_modules/node-red/node_modules/clone/clone.js:162:18)
Jun 29 21:52:48 nodered sudo[25427]:     at _clone (/usr/local/lib/node_modules/node-red/node_modules/clone/clone.js:162:18)
Jun 29 21:52:48 nodered sudo[25427]:     at _clone (/usr/local/lib/node_modules/node-red/node_modules/clone/clone.js:162:18)
Jun 29 21:52:48 nodered sudo[25427]:     at _clone (/usr/local/lib/node_modules/node-red/node_modules/clone/clone.js:162:18)
Jun 29 21:52:48 nodered sudo[25427]:     at /usr/local/lib/node_modules/node-red/node_modules/clone/clone.js:142:26
Jun 29 21:52:48 nodered sudo[25427]:     at Map.forEach (<anonymous>)
Jun 29 21:52:48 nodered sudo[25427]:     at _clone (/usr/local/lib/node_modules/node-red/node_modules/clone/clone.js:140:14)
Jun 29 21:52:48 nodered sudo[25427]:     at _clone (/usr/local/lib/node_modules/node-red/node_modules/clone/clone.js:162:18)
Jun 29 21:52:48 nodered sudo[25427]:     at _clone (/usr/local/lib/node_modules/node-red/node_modules/clone/clone.js:162:18)
Jun 29 21:52:48 nodered sudo[25427]:     at _clone (/usr/local/lib/node_modules/node-red/node_modules/clone/clone.js:162:18)
Jun 29 21:52:48 nodered sudo[25427]:     at _clone (/usr/local/lib/node_modules/node-red/node_modules/clone/clone.js:162:18)
Jun 29 21:52:48 nodered sudo[25427]:     at clone (/usr/local/lib/node_modules/node-red/node_modules/clone/clone.js:202:10)
Jun 29 21:52:48 nodered sudo[25427]:     at Object.cloneMessage (/usr/local/lib/node_modules/node-red/node_modules/@node-red/util/lib/util.js:90:13)
Jun 29 21:52:48 nodered sudo[25427]:     at DiscordInNode.Node.send (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:199:61)
Jun 29 21:52:48 nodered sudo[25427]:     at /home/ubuntu/.node-red/node_modules/node-red-contrib-chatbot/nodes/chatbot-discord-receive.js:208:22
Jun 29 21:52:48 nodered sudo[25427]:     at process._tickCallback (internal/process/next_tick.js:68:7)
Jun 29 21:52:48 nodered sudo[25427]: (node:25428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
 UnhandledPromiseRejectionWarning: TypeError: Cannot assign to read only property 'writeQueueSize' of object '#<TCP>'

```

**Comment by guidone** [comment]
Can you make a screenshot of the flow? What do you mean with manipulate?

**Comment by dfit** [comment]
During my test I reproduced this issue with the extend server node, I had to ctrl x restart flows ctrl v him to pass the problem

**Comment by alokt** [comment]
Having exact same issue with discord node. @dfit can you please explain how did you fix this issue?

**Comment by dfit** [comment]
Can you show me your flow?

**Comment by alokt** [comment]
Node for discord is removed from the original bundle and added into separate repo. I did fresh install and now its working. 
https://github.com/guidone/node-red-contrib-chatbot/blob/master/CHANGELOG.md

**Comment by pratham2003** [comment]
I'm still having this issue.
My flow is simple.
`Discord Receiver` --> `Debug` (This produces the OP's error)

But just an FYI.
`Discord Receiver` --> `Text` --> `Discord Sender` works as expected.
