### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by ram1505** [guidone/node-red-contrib-chatbot#33]
Hi,
When I send a command from Slack, node-red abruptly terminates with the following error:

`
15 Dec 13:20:18 - [red] Uncaught Exception:
15 Dec 13:20:18 - ReferenceError: self is not defined
    at RTMClient.<anonymous> (/home/pi/.node-red/node_modules/node-red-contrib-c                              hatbot/chatbot-slack-receive.js:142:69)
    at RTMClient.emit (/home/pi/.node-red/node_modules/eventemitter3/index.js:11                              6:35)
    at RTMClient.emit (/home/pi/.node-red/node_modules/@slack/client/lib/clients                              /client.js:83:39)
    at RTMClient._handleWsMessageViaEventHandler (/home/pi/.node-red/node_module                              s/@slack/client/lib/clients/rtm/client.js:466:10)
    at RTMClient.handleWsMessage (/home/pi/.node-red/node_modules/@slack/client/                              lib/clients/rtm/client.js:420:10)
    at WebSocket.wrapper (/home/pi/.node-red/node_modules/@slack/client/node_mod                              ules/lodash/lodash.js:4921:19)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (/home/pi/.node-red/node_modules/@slack/client/node_modul                              es/ws/lib/WebSocket.js:841:10)
    at /home/pi/.node-red/node_modules/@slack/client/node_modules/ws/lib/Receive                              r.js:536:18
    at Receiver.applyExtensions (/home/pi/.node-red/node_modules/@slack/client/n                              ode_modules/ws/lib/Receiver.js:371:5)
    at /home/pi/.node-red/node_modules/@slack/client/node_modules/ws/lib/Receive                              r.js:508:14
    at Receiver.flush (/home/pi/.node-red/node_modules/@slack/client/node_module                              s/ws/lib/Receiver.js:347:3)
    at Receiver.opcodes.1.finish (/home/pi/.node-red/node_modules/@slack/client/                              node_modules/ws/lib/Receiver.js:541:12)
    at Receiver.expectHandler (/home/pi/.node-red/node_modules/@slack/client/nod                              e_modules/ws/lib/Receiver.js:499:31)
    at Receiver.add (/home/pi/.node-red/node_modules/@slack/client/node_modules/                              ws/lib/Receiver.js:103:24)
    at TLSSocket.realHandler (/home/pi/.node-red/node_modules/@slack/client/node                              _modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at TLSSocket.Readable.push (_stream_readable.js:111:10)
    at TLSWrap.onread (net.js:537:20)
`

**Comment by guidone** [comment]
Yes @ram1505 the Slack node requires some attention, in the new weeks I'll find some times to fix it and also answer your question about API.ai

**Comment by ram1505** [comment]
Thanks

**Comment by stejsoftware** [comment]
I've submitted a possible fix to this problem. https://github.com/guidone/node-red-contrib-chatbot/pull/37

**Comment by guidone** [comment]
thanks @stejsoftware , it's merged
