### ISSUE TITLE
Does node red support Slack event subscriptions?

### ISSUE THREAD

**Issue by TroyMorvant** [guidone/node-red-contrib-chatbot#373]
I'm having trouble getting my redbot to respond to slack events. In order to enable events in slack I  need to respond to the `url_verification` event with the challenge token that was sent, however when slack sends the challenge message, ngrok returns a 500 and the following is logged to the console:

```------ WebHooks for SLACK----------------
   http://localhost:1880/redbot/slack/command/ - Endpoint for Slack command
   http://localhost:1880/redbot/slack/test/ - Use this to test that your SSL (with certificate or ngrok) is working properly, should answer "ok"
   http://localhost:1880/redbot/slack/ - Use this in the "Request URL" of the "Interactive Components" of your Slack App
   
   Chat server started, transport: slack
   TypeError: Cannot read property 'type' of null
       at ChatServer./redbot/slack (/data/node_modules/node-red-contrib-chatbot/lib/platforms/slack.js:149:26)
       at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
       at trim_prefix (/usr/src/node-red/node_modules/express/lib/router/index.js:317:13)
       at /usr/src/node-red/node_modules/express/lib/router/index.js:284:7
       at Function.process_params (/usr/src/node-red/node_modules/express/lib/router/index.js:335:12)
       at next (/usr/src/node-red/node_modules/express/lib/router/index.js:275:10)
       at compression (/data/node_modules/compression/index.js:220:5)
       at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
       at trim_prefix (/usr/src/node-red/node_modules/express/lib/router/index.js:317:13)
       at /usr/src/node-red/node_modules/express/lib/router/index.js:284:7
       at Function.process_params (/usr/src/node-red/node_modules/express/lib/router/index.js:335:12)
       at next (/usr/src/node-red/node_modules/express/lib/router/index.js:275:10)
       at expressInit (/usr/src/node-red/node_modules/express/lib/middleware/init.js:40:5)
       at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
       at trim_prefix (/usr/src/node-red/node_modules/express/lib/router/index.js:317:13)
       at /usr/src/node-red/node_modules/express/lib/router/index.js:284:7
       at Function.process_params (/usr/src/node-red/node_modules/express/lib/router/index.js:335:12)
       at next (/usr/src/node-red/node_modules/express/lib/router/index.js:275:10)
       at query (/usr/src/node-red/node_modules/express/lib/middleware/query.js:45:5)
       at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
       at trim_prefix (/usr/src/node-red/node_modules/express/lib/router/index.js:317:13)
       at /usr/src/node-red/node_modules/express/lib/router/index.js:284:7 
```

I see a route for `./commands` and `./messages`, but nothing for `./events` or `./actions` so I just configured slack to post the challenge message to the same route it uses for messages: 
 `./redbot/slack`.

Are slack events supported?  Do I need to use the extend chat server node to accomplish this?

**Comment by guidone** [comment]
I'm working on this

**Comment by guidone** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Slack Events](https://trello.com/c/HUC04URX/28-slack-events)

**Comment by guidone** [comment]
Events are now supported in `0.18.5`

**Comment by rcarmo** [comment]
I have 0.18.15 and am having _exactly_ the same error. I've added a couple of `console.log()` calls and have verified that `payload` is `null` on that same line.

I on the Slack side, I get a message stating that "Request URL: Your URL didn't respond with the value of the challenge parameter."
