### ISSUE TITLE
MSTeams - Missing Activity Type

### ISSUE THREAD

**Issue by arnydo** [guidone/node-red-contrib-chatbot#389]
Configured MSTeams node per documentation and receiving the following error. Is this an indication of an error on the Node-Red side or MSTeams side?
```
(node:16) UnhandledPromiseRejectionWarning: Error: BotFrameworkAdapter.processActivity(): 400 ERROR
 Error: BotFrameworkAdapter.parseRequest(): missing activity type.
    at returnActivity (/data/node_modules/botbuilder/lib/botFrameworkAdapter.js:1225:23)
    at Promise (/data/node_modules/botbuilder/lib/botFrameworkAdapter.js:1240:17)
    at new Promise (<anonymous>)
    at parseRequest (/data/node_modules/botbuilder/lib/botFrameworkAdapter.js:1219:12)
    at BotFrameworkAdapter.<anonymous> (/data/node_modules/botbuilder/lib/botFrameworkAdapter.js:638:39)
    at Generator.next (<anonymous>)
    at /data/node_modules/botbuilder/lib/botFrameworkAdapter.js:14:71
    at new Promise (<anonymous>)
    at __awaiter (/data/node_modules/botbuilder/lib/botFrameworkAdapter.js:10:12)
    at BotFrameworkAdapter.processActivity (/data/node_modules/botbuilder/lib/botFrameworkAdapter.js:631:16)
    at resolve (/data/node_modules/node-red-contrib-chatbot/lib/platforms/microsoft-teams/index.js:96:22)
    at new Promise (<anonymous>)
    at ChatServer.getActivity (/data/node_modules/node-red-contrib-chatbot/lib/platforms/microsoft-teams/index.js:95:12)    at ChatServer./redbot/msteams (/data/node_modules/node-red-contrib-chatbot/lib/platforms/microsoft-teams/index.js:67:35)
    at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/node-red/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/node-red/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/node-red/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/node-red/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/usr/src/node-red/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/node-red/node_modules/express/lib/router/index.js:317:13)
    at BotFrameworkAdapter.<anonymous> (/data/node_modules/botbuilder/lib/botFrameworkAdapter.js:681:27)
    at Generator.throw (<anonymous>)
    at rejected (/data/node_modules/botbuilder/lib/botFrameworkAdapter.js:12:65)
(node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 30)
```

**Comment by arnydo** [comment]
Not sure if this is related. Verified correct AppID/Pass:

```(node:16) UnhandledPromiseRejectionWarning: Error: BotFrameworkAdapter.processActivity(): 401 ERROR
 Error: Unauthorized. Invalid AppId passed on token: eee09047-5d30-4c26-b65f-f83ca05707c4
    at /data/node_modules/botframework-connector/lib/auth/channelValidation.js:90:23
    at Generator.next (<anonymous>)
    at fulfilled (/data/node_modules/botframework-connector/lib/auth/channelValidation.js:4:58)
    at BotFrameworkAdapter.<anonymous> (/data/node_modules/botbuilder/lib/botFrameworkAdapter.js:681:27)
    at Generator.throw (<anonymous>)
    at rejected (/data/node_modules/botbuilder/lib/botFrameworkAdapter.js:12:65)
(node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 44)```
