### ISSUE TITLE
Slack Event Registration Fails (#373 should be reopened)

### ISSUE THREAD

**Issue by rcarmo** [guidone/node-red-contrib-chatbot#403]
I have been trying to get RedBot to subscribe to Slack events for a little while now, and have established that #373 is still a thing in 0.18.15.

I have these versions installed through `package.json`:

```json
{
  "dependencies": {
    "node-red": "^1.0.4",
    "body-parser": "^1.19.0",
    "node-red-contrib-average": "^0.1.7",
    "node-red-contrib-chatbot": "^0.18.15",
    "node-red-contrib-linux-diskio": "^0.2.1",
    "node-red-contrib-linux-memory": "^0.8.1",
    "node-red-contrib-linux-network-stats": "^0.2.1",
    "node-red-contrib-os": "^0.1.7",
    "node-red-contrib-persist": "^1.0.3",
    "node-red-dashboard": "^2.19.4",
    "node-red-node-rbe": "^0.2.8",
    "node-red-node-smooth": "^0.1.2",
    "node-red-node-tail": "^0.1.1",
    "node-red-node-ui-table": "^0.3.0"
  },
  "description": "Node-Red example.",
  "name": "deploy-redbot"
}
```

...which I can verify from the `npm` output:

```
remote: ├─┬ node-red-contrib-chatbot@0.18.15 
remote: │ ├─┬ @slack/client@4.12.0 
```

When I try to register event handling in Slack, this is what I get in the Slack front-end:

![image-1](https://user-images.githubusercontent.com/392683/77093809-73e42880-6a03-11ea-8dc0-84cb7463b29c.png)

...and this is what I get in the back-end:

```
web.1 | TypeError: Cannot read property 'type' of null
web.1 |     at ChatServer./redbot/slack (/home/piku/.piku/envs/nodered/node_modules/node-red-contrib-chatbot/lib/platforms/slack.js:129:19)
web.1 |     at Layer.handle [as handle_request] (/home/piku/.piku/envs/nodered/node_modules/express/lib/router/layer.js:95:5)
web.1 |     at trim_prefix (/home/piku/.piku/envs/nodered/node_modules/express/lib/router/index.js:317:13)
web.1 |     at /home/piku/.piku/envs/nodered/node_modules/express/lib/router/index.js:284:7
web.1 |     at Function.process_params (/home/piku/.piku/envs/nodered/node_modules/express/lib/router/index.js:335:12)
web.1 |     at next (/home/piku/.piku/envs/nodered/node_modules/express/lib/router/index.js:275:10)
web.1 |     at serveStatic (/home/piku/.piku/envs/nodered/node_modules/serve-static/index.js:75:16)
web.1 |     at Layer.handle [as handle_request] (/home/piku/.piku/envs/nodered/node_modules/express/lib/router/layer.js:95:5)
web.1 |     at trim_prefix (/home/piku/.piku/envs/nodered/node_modules/express/lib/router/index.js:317:13)
web.1 |     at /home/piku/.piku/envs/nodered/node_modules/express/lib/router/index.js:284:7
web.1 |     at Function.process_params (/home/piku/.piku/envs/nodered/node_modules/express/lib/router/index.js:335:12)
web.1 |     at next (/home/piku/.piku/envs/nodered/node_modules/express/lib/router/index.js:275:10)
web.1 |     at dashboardMiddleware (/home/piku/.piku/envs/nodered/node_modules/node-red-dashboard/ui.js:337:58)
web.1 |     at Layer.handle [as handle_request] (/home/piku/.piku/envs/nodered/node_modules/express/lib/router/layer.js:95:5)
web.1 |     at trim_prefix (/home/piku/.piku/envs/nodered/node_modules/express/lib/router/index.js:317:13)
web.1 |     at /home/piku/.piku/envs/nodered/node_modules/express/lib/router/index.js:284:7
web.1 |     at Function.process_params (/home/piku/.piku/envs/nodered/node_modules/express/lib/router/index.js:335:12)
web.1 |     at next (/home/piku/.piku/envs/nodered/node_modules/express/lib/router/index.js:275:10)
web.1 |     at compression (/home/piku/.piku/envs/nodered/node_modules/compression/index.js:220:5)
web.1 |     at Layer.handle [as handle_request] (/home/piku/.piku/envs/nodered/node_modules/express/lib/router/layer.js:95:5)
web.1 |     at trim_prefix (/home/piku/.piku/envs/nodered/node_modules/express/lib/router/index.js:317:13)
web.1 |     at /home/piku/.piku/envs/nodered/node_modules/express/lib/router/index.js:284:7
```

The only way I managed to get this to work (for a bit) was opening up port 1880 in my home router and subscribing to that URL in Slack. 

Adding `nginx` as a reverse proxy (with or without HTTPS) causes this to break, even though I can see the full HTTP 1.1 headers Slack sends if I put a little shell script behind `nginx`. 

I also can't see _anything_ on the Node-RED debug pane, or anything else in the console log, which makes it quite hard to debug this. I've tried Node 8, 10, and 12, too.

**Comment by guidone** [comment]
There is a complete refactoring of Slack connector in `0.19.4`
