### ISSUE TITLE
[VIBER] Viber server is unable to reach web hook

### ISSUE THREAD

**Issue by jlaszloe6** [guidone/node-red-contrib-chatbot#406]
I am running Node-RED and node-red-contrib-chatbot (0.18.15) on IBM Cloud.
During the configuration and deploy of the Viber Receiver node I got error: "[VIBER] Viber server is unable to reach web hook: https://rtd-node-red.eu-gb.mybluemix.net/redbot/viber Check you internet connection, this address must be reachable outside your local network"

In the server log I got the following error messages:

APP/PROC/WEB	0	TypeError: Cannot read property 'event' of undefined	8 Apr 202008:33:43.350 AM
APP/PROC/WEB	0	at ChatServer./redbot/viber (/home/vcap/deps/0/node_modules/node-red-contrib-chatbot/lib/platforms/viber.js:103:20)	8 Apr 202008:33:43.350 AM
APP/PROC/WEB	0	at Layer.handle [as handle_request] (/home/vcap/deps/0/node_modules/express/lib/router/layer.js:95:5)	8 Apr 202008:33:43.350 AM
APP/PROC/WEB	0	at trim_prefix (/home/vcap/deps/0/node_modules/express/lib/router/index.js:317:13)	8 Apr 202008:33:43.350 AM
APP/PROC/WEB	0	at /home/vcap/deps/0/node_modules/express/lib/router/index.js:284:7	8 Apr 202008:33:43.350 AM
APP/PROC/WEB	0	at Function.process_params (/home/vcap/deps/0/node_modules/express/lib/router/index.js:335:12)	8 Apr 202008:33:43.350 AM
APP/PROC/WEB	0	at next (/home/vcap/deps/0/node_modules/express/lib/router/index.js:275:10)	8 Apr 202008:33:43.350 AM
APP/PROC/WEB	0	at compression (/home/vcap/deps/0/node_modules/compression/index.js:220:5)	8 Apr 202008:33:43.350 AM
APP/PROC/WEB	0	at Layer.handle [as handle_request] (/home/vcap/deps/0/node_modules/express/lib/router/layer.js:95:5)	8 Apr 202008:33:43.350 AM
APP/PROC/WEB	0	at trim_prefix (/home/vcap/deps/0/node_modules/express/lib/router/index.js:317:13)	8 Apr 202008:33:43.350 AM
APP/PROC/WEB	0	at /home/vcap/deps/0/node_modules/express/lib/router/index.js:284:7	8 Apr 202008:33:43.350 AM
APP/PROC/WEB	0	at Function.process_params (/home/vcap/deps/0/node_modules/express/lib/router/index.js:335:12)	8 Apr 202008:33:43.350 AM
APP/PROC/WEB	0	at next (/home/vcap/deps/0/node_modules/express/lib/router/index.js:275:10)	8 Apr 202008:33:43.350 AM
APP/PROC/WEB	0	at expressInit (/home/vcap/deps/0/node_modules/express/lib/middleware/init.js:40:5)	8 Apr 202008:33:43.350 AM
APP/PROC/WEB	0	at Layer.handle [as handle_request] (/home/vcap/deps/0/node_modules/express/lib/router/layer.js:95:5)	8 Apr 202008:33:43.350 AM
APP/PROC/WEB	0	at trim_prefix (/home/vcap/deps/0/node_modules/express/lib/router/index.js:317:13)	8 Apr 202008:33:43.350 AM
APP/PROC/WEB	0	at /home/vcap/deps/0/node_modules/express/lib/router/index.js:284:7	8 Apr 202008:33:43.350 AM
APP/PROC/WEB	0	at Function.process_params (/home/vcap/deps/0/node_modules/express/lib/router/index.js:335:12)	8 Apr 202008:33:43.350 AM
APP/PROC/WEB	0	at next (/home/vcap/deps/0/node_modules/express/lib/router/index.js:275:10)	8 Apr 202008:33:43.350 AM
APP/PROC/WEB	0	at query (/home/vcap/deps/0/node_modules/express/lib/middleware/query.js:45:5)	8 Apr 202008:33:43.350 AM
APP/PROC/WEB	0	at Layer.handle [as handle_request] (/home/vcap/deps/0/node_modules/express/lib/router/layer.js:95:5)	8 Apr 202008:33:43.350 AM
APP/PROC/WEB	0	at trim_prefix (/home/vcap/deps/0/node_modules/express/lib/router/index.js:317:13)	8 Apr 202008:33:43.350 AM
APP/PROC/WEB	0	at /home/vcap/deps/0/node_modules/express/lib/router/index.js:284:7	8 Apr 202008:33:43.350 AM
RTR	11	rtd-node-red.eu-gb.mybluemix.net - [2020-04-08T06:33:43.177090410Z] "GET /redbot/viber HTTP/1.1" 500 0 148 "-" "PostmanRuntime/7.24.0" "10.112.95.69:42859" "141.125.76.77:61172" x_forwarded_for:"89.223.191.136, 10.112.95.69" x_forwarded_proto:"https" vcap_request_id:"8340a062-dd83-4cf4-78a4-31fdbc2b8979" response_time:0.171405 gorouter_time:0.000191 app_id:"f113e0ba-e2b8-4358-bf70-8376ab71b1c2" app_index:"0" x_global_transaction_id:"086c0fe95e8d704738a1ff6f" true_client_ip:"-" x_b3_traceid:"32a64c99b24bef60" x_b3_spanid:"32a64c99b24bef60" x_b3_parentspanid:"-" b3:"32a64c99b24bef60-32a64c99b24bef60"	8 Apr 202008:33:43.349 AM

In case I just simply expose a http request node on https://rtd-node-red.eu-gb.mybluemix.net/redbot/viber URL that works fine. Error only comes if the Viber Receiver node is configured and deployed.

Could you please help?

**Comment by DanielJRusev** [comment]
im having the same problem. Any recommendations how to solve ?

**Comment by DanielJRusev** [comment]
I've solve this problem by adding  RED.httpNode.use(bodyParser.json())  on line 630 in chat-platform.js
