### ISSUE TITLE
Telegram: UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'en' of undefined

### ISSUE THREAD

**Issue by bkupidura** [guidone/node-red-contrib-chatbot#434]
Hey,
I playing with chatbot, but after couple of hours it stops processing messages.

```
(node:16) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'en' of undefined
    at NeuralNlu.defaultPipelinePrepare (/data/node_modules/@nlpjs/nlu/src/nlu.js:96:34)
    at NeuralNlu.prepare (/data/node_modules/@nlpjs/nlu/src/nlu.js:141:19)
    at DomainManager.prepare (/data/node_modules/@nlpjs/nlu/src/domain-manager.js:214:24)
    at DomainManager.generateStemKey (/data/node_modules/@nlpjs/nlu/src/domain-manager.js:120:32)
    at DomainManager.classifyByStemDict (/data/node_modules/@nlpjs/nlu/src/domain-manager.js:261:28)
    at DomainManager.innerClassify (/data/node_modules/@nlpjs/nlu/src/domain-manager.js:284:33)
    at DomainManager.defaultPipelineProcess (/data/node_modules/@nlpjs/nlu/src/domain-manager.js:364:31)
    at DomainManager.process (/data/node_modules/@nlpjs/nlu/src/domain-manager.js:379:17)
    at NluManager.innerClassify (/data/node_modules/@nlpjs/nlu/src/nlu-manager.js:285:42)
    at NluManager.defaultPipelineProcess (/data/node_modules/@nlpjs/nlu/src/nlu-manager.js:307:25)
    at runNextTicks (internal/process/task_queues.js:62:5)
    at processImmediate (internal/timers.js:429:9)
    at async Nlp.process (/data/node_modules/@nlpjs/nlp/src/nlp.js:485:18)
    at async NlpManager.process (/data/node_modules/node-nlp/src/nlp/nlp-manager.js:211:20)
    at async ChatBotNLPjs._inputCallback (/data/node_modules/node-red-contrib-chatbot/nodes/chatbot-nlp.js:86:24)
(node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 92)
```

Node-red running in container.
node-red version 1.1.3-12
node-red-contrib-chatbot version 0.19.3

My flow is very basic (telegram receiver -> authorized -> NLP.js proccess)

<img width="536" alt="Screenshot 2020-08-11 at 20 23 28" src="https://user-images.githubusercontent.com/4814684/89934235-8e1bde80-dc10-11ea-8a0f-6cda1f479f0f.png">

If i will restart node-red, flow will work for couple of hours - but finally it will end in broken state.

**Comment by bkupidura** [comment]
Afaik this is issue with nlp.js. I created issue there: https://github.com/axa-group/nlp.js/issues/543

**Comment by bkupidura** [comment]
Looks like issue was solved in nlp 4.10.4. Can we bump dependencies for chatbot?

**Comment by guidone** [comment]
Sure, sorry for the delay, vacation time.

**Comment by guidone** [comment]
Done in `0.19.7`
