### ISSUE TITLE
Can't install ,deprecated npm

### ISSUE THREAD

**Issue by Maurotb** [guidone/node-red-contrib-chatbot#442]
Hi,
if i add a palette in my node-red 1.1.3 i have this error
thanks

2020-10-15T19:19:50.381Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix="~" --production node-red-contrib-chatbot@0.19.7
2020-10-15T19:19:58.785Z [err] npm
2020-10-15T19:19:58.786Z [err]  
2020-10-15T19:19:58.786Z [err] WARN
2020-10-15T19:19:58.787Z [err]  
2020-10-15T19:19:58.787Z [err] deprecated
2020-10-15T19:19:58.788Z [err]  request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
2020-10-15T19:20:01.193Z [err] npm
2020-10-15T19:20:01.194Z [err]  
2020-10-15T19:20:01.195Z [err] ERR!
2020-10-15T19:20:01.208Z [err]  Unexpected end of JSON input while parsing near '...m":"8d17b2d22f30d73a4'
2020-10-15T19:20:01.273Z [err] 
2020-10-15T19:20:01.275Z [err] npm
2020-10-15T19:20:01.275Z [err]  
2020-10-15T19:20:01.300Z [err] ERR!
2020-10-15T19:20:01.301Z [err]  A complete log of this run can be found in:
2020-10-15T19:20:01.315Z [err] npm
2020-10-15T19:20:01.315Z [err]  ERR!     /root/.npm/_logs/2020-10-15T19_20_01_220Z-debug.log
2020-10-15T19:20:01.493Z rc=1

**Comment by rwit-ormer** [comment]
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npmjs.org/fast-levenshtein/-/fast-levenshtein-2.0.6.tgz failed, reason: connect ETIMEDOUT 104.16.19.35:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-26T15_31_23_247Z-debug.log

**Comment by rwit-ormer** [comment]
Configuration:
system_packages:
  - ffmpeg
  - make
  - g++
  - gcc
  - python3
  - linux-headers
npm_packages:
  - node-pre-gyp

######

-----------------------------------------------------------
2020-10-29T20:14:22.992Z Install : node-red-contrib-chatbot 0.19.7

2020-10-29T20:14:23.228Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix="~" --production node-red-contrib-chatbot@0.19.7
2020-10-29T20:18:38.279Z [err] npm
2020-10-29T20:18:38.280Z [err]  WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
2020-10-29T20:18:38.294Z [err] npm
2020-10-29T20:18:38.295Z [err]  WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
2020-10-29T20:20:38.632Z [err] npm
2020-10-29T20:20:38.633Z [err]  WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
2020-10-29T20:20:47.822Z [err] npm
2020-10-29T20:20:47.823Z [err]  WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
2020-10-29T20:38:56.941Z [out] 
2020-10-29T20:38:56.941Z [out] > sqlite3@4.2.0 install /config/node-red/node_modules/sqlite3
2020-10-29T20:38:56.941Z [out] > node-pre-gyp install --fallback-to-build
2020-10-29T20:38:56.941Z [out] 
2020-10-29T20:40:16.471Z [err] node-pre-gyp
2020-10-29T20:40:16.535Z [err]  WARN Using request for node-pre-gyp https download 
2020-10-29T20:40:55.942Z [err] node-pre-gyp WARN Pre-built binaries not installable for sqlite3@4.2.0 and node@12.18.4 (node-v72 ABI, musl) (falling back to source compile with node-gyp) 
2020-10-29T20:40:55.942Z [err] node-pre-gyp WARN Hit error connect ETIMEDOUT 52.217.82.28:443 
2020-10-29T20:43:12.079Z [out] make: Entering directory '/config/node-red/node_modules/sqlite3/build'
2020-10-29T20:43:12.126Z [out]   ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c
2020-10-29T20:43:12.150Z [err] /bin/sh: python: not found
2020-10-29T20:43:12.151Z [err] make: *** [deps/action_before_build.target.mk:13: Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c] Error 127
2020-10-29T20:43:12.152Z [out] make: Leaving directory '/config/node-red/node_modules/sqlite3/build'
2020-10-29T20:43:12.185Z [err] gyp
2020-10-29T20:43:12.211Z [err]  
2020-10-29T20:43:12.211Z [err] ERR! build error 
2020-10-29T20:43:12.251Z [err] gyp
2020-10-29T20:43:12.252Z [err]  
2020-10-29T20:43:12.287Z [err] ERR!
2020-10-29T20:43:12.289Z [err]  stack Error: `make` failed with exit code: 2
2020-10-29T20:43:12.289Z [err] gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
2020-10-29T20:43:12.289Z [err] gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
2020-10-29T20:43:12.289Z [err] gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
2020-10-29T20:43:12.289Z [err] gyp ERR! System Linux 4.19.127-v7
2020-10-29T20:43:12.289Z [err] gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/config/node-red/node_modules/sqlite3/lib/binding/node-v72-linux-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/config/node-red/node_modules/sqlite3/lib/binding/node-v72-linux-arm" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
2020-10-29T20:43:12.289Z [err] gyp ERR! cwd /config/node-red/node_modules/sqlite3
2020-10-29T20:43:12.289Z [err] gyp ERR! node -v v12.18.4
2020-10-29T20:43:12.289Z [err] gyp ERR! node-gyp -v v5.1.0
2020-10-29T20:43:12.289Z [err] gyp ERR! not ok 
2020-10-29T20:43:12.498Z [err] node-pre-gyp
2020-10-29T20:43:12.500Z [err]  
2020-10-29T20:43:12.501Z [err] ERR!
2020-10-29T20:43:12.502Z [err]  build error 
2020-10-29T20:43:12.507Z [err] node-pre-gyp
2020-10-29T20:43:12.508Z [err]  ERR! stack
2020-10-29T20:43:12.508Z [err]  Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/config/node-red/node_modules/sqlite3/lib/binding/node-v72-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/config/node-red/node_modules/sqlite3/lib/binding/node-v72-linux-arm --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
2020-10-29T20:43:12.508Z [err] node-pre-gyp ERR!
2020-10-29T20:43:12.509Z [err]  stack
2020-10-29T20:43:12.509Z [err]      at ChildProcess.<anonymous> (/config/node-red/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
2020-10-29T20:43:12.509Z [err] node-pre-gyp ERR! 
2020-10-29T20:43:12.510Z [err] stack     at ChildProcess.emit (events.js:315:20)
2020-10-29T20:43:12.510Z [err] node-pre-gyp 
2020-10-29T20:43:12.511Z [err] ERR! stack     at maybeClose (internal/child_process.js:1021:16)
2020-10-29T20:43:12.511Z [err] node-pre-gyp ERR! stack
2020-10-29T20:43:12.512Z [err]      at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
2020-10-29T20:43:12.515Z [err] node-pre-gyp
2020-10-29T20:43:12.515Z [err]  ERR! System Linux 4.19.127-v7
2020-10-29T20:43:12.515Z [err] node-pre-gyp ERR!
2020-10-29T20:43:12.516Z [err]  command "/usr/bin/node" "/config/node-red/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
2020-10-29T20:43:12.516Z [err] node-pre-gyp ERR!
2020-10-29T20:43:12.516Z [err]  cwd /config/node-red/node_modules/sqlite3
2020-10-29T20:43:12.516Z [err] node-pre-gyp ERR! 
2020-10-29T20:43:12.516Z [err] node -v v12.18.4
2020-10-29T20:43:12.519Z [err] node-pre-gyp 
2020-10-29T20:43:12.519Z [err] ERR! node-pre-gyp -v v0.11.0
2020-10-29T20:43:12.519Z [err] node-pre-gyp
2020-10-29T20:43:12.519Z [err]  ERR! not ok 
2020-10-29T20:43:12.531Z [out] Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/config/node-red/node_modules/sqlite3/lib/binding/node-v72-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/config/node-red/node_modules/sqlite3/lib/binding/node-v72-linux-arm --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
2020-10-29T20:43:29.317Z [err] npm
2020-10-29T20:43:29.346Z [err]  
2020-10-29T20:43:29.346Z [err] WARN babel-loader@7.1.5 requires a peer of babel-core@6 but none is installed. You must install peer dependencies yourself.
2020-10-29T20:43:29.403Z [err] npm WARN babel-loader@7.1.5 requires a peer of webpack@2 || 3 || 4 but none is installed. You must install peer dependencies yourself.
2020-10-29T20:43:29.487Z [err] 
2020-10-29T20:43:30.732Z [err] npm
2020-10-29T20:43:30.733Z [err]  ERR! code ELIFECYCLE
2020-10-29T20:43:30.733Z [err] npm
2020-10-29T20:43:30.733Z [err]  
2020-10-29T20:43:30.747Z [err] ERR!
2020-10-29T20:43:30.748Z [err]  errno 1
2020-10-29T20:43:30.796Z [err] npm ERR!
2020-10-29T20:43:30.796Z [err]  sqlite3@4.2.0 install: `node-pre-gyp install --fallback-to-build`
2020-10-29T20:43:30.796Z [err] npm ERR! Exit status 1
2020-10-29T20:43:30.796Z [err] npm 
2020-10-29T20:43:30.797Z [err] ERR! 
2020-10-29T20:43:30.797Z [err] npm ERR! Failed at the sqlite3@4.2.0 install script.
2020-10-29T20:43:30.797Z [err] npm ERR!
2020-10-29T20:43:30.797Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
2020-10-29T20:43:31.850Z [err] 
2020-10-29T20:43:31.850Z [err] npm ERR! A complete log of this run can be found in:
2020-10-29T20:43:31.850Z [err] npm ERR!     /root/.npm/_logs/2020-10-29T20_43_31_214Z-debug.log
2020-10-29T20:43:32.549Z rc=1

**Comment by haziqmus** [comment]
same here, cant install

**Comment by Elgger** [comment]
Same here, can't install on my Plesk Onyx server : 

`    npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
    npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
    npm WARN deprecated har-validator@5.1.5: this library is no longer supported
    npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
    npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
    npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
    npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
    npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
    npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
    npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
    npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
    npm WARN lifecycle npm is using /opt/plesk/node/12/bin/node but there is no node binary in the current PATH. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
    /usr/bin/env: 'node': No such file or directory
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.3 (node_modules/sane/node_modules/fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
    npm WARN twilio@3.54.0 requires a peer of @types/qs@6.9.4 but none is installed. You must install peer dependencies yourself.
    npm WARN ws@7.4.1 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
    npm WARN ws@7.4.1 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
    npm WARN babel-loader@7.1.5 requires a peer of webpack@2 || 3 || 4 but none is installed. You must install peer dependencies yourself.
    npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
    npm ERR! file sh
    npm ERR! code ELIFECYCLE
    npm ERR! errno ENOENT
    npm ERR! syscall spawn
    npm ERR! grpc@1.24.4 install: `node-pre-gyp install --fallback-to-build --library=static_library`
    npm ERR! spawn ENOENT
    npm ERR!
    npm ERR! Failed at the grpc@1.24.4 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    npm ERR! A complete log of this run can be found in:
    npm ERR! /var/www/vhosts/mydomain.fr/.npm/_logs/2020-12-09T13_33_05_482Z-debug.log`

**Comment by polcape** [comment]
Same problem, did you solve?

**Comment by guidone** [comment]
The warn doesn't prevent the install, the library is deprecated but still working (a lot of projects rely on it)

**Comment by polcape** [comment]
Yes, @guidone! You are right.

I successfully used redbot!
