### ISSUE TITLE
Node Red installation fails

### ISSUE THREAD

**Issue by BatterBits** [guidone/node-red-contrib-chatbot#493]
Hi,

I am trying to install in HA but getting a slew of errors.

My system is NR(Ver 1.3.5) running as an HomeAssistant Addon, with HA(Ver 2021.8.6 running as a virtual Appliance in my QNAP NAS.

I am able to add other pallets to my NR instance. I did try to connect to the Slack group but the invites are all not working - I looked at the trello board, but it didn't seem appropriate for me to raise the query there.

Is anyone able to assist or even point me in the right direction please?

Here is the error log:

-----------------------------------------------------------
2021-08-12T08:59:57.117Z Install : node-red-contrib-chatbot 0.19.7

2021-08-12T08:59:57.690Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-chatbot@0.19.7
2021-08-12T09:11:38.183Z [err] npm
2021-08-12T09:11:38.197Z [err]  WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
2021-08-12T09:11:50.869Z [err] npm
2021-08-12T09:11:50.902Z [err]  WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
2021-08-12T09:11:54.179Z [err] npm
2021-08-12T09:11:54.181Z [err]  
2021-08-12T09:11:54.182Z [err] WARN
2021-08-12T09:11:54.184Z [err]  
2021-08-12T09:11:54.186Z [err] deprecated
2021-08-12T09:11:54.187Z [err]  socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
2021-08-12T09:11:56.329Z [err] npm
2021-08-12T09:11:56.332Z [err]  WARN 
2021-08-12T09:11:56.334Z [err] deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
2021-08-12T09:11:57.329Z [err] npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
2021-08-12T09:14:00.592Z [err] npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
2021-08-12T09:15:45.851Z [err] npm
2021-08-12T09:15:45.853Z [err]  WARN deprecated axios@0.18.1: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
2021-08-12T09:15:48.151Z [err] npm WARN deprecated axios@0.18.1: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
2021-08-12T09:19:30.135Z [err] npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
2021-08-12T09:19:30.545Z [err] npm
2021-08-12T09:19:30.554Z [err]  WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
2021-08-12T09:19:30.710Z [err] npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
2021-08-12T09:19:31.049Z [err] npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
2021-08-12T09:19:31.281Z [err] npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
2021-08-12T09:19:31.378Z [err] npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
2021-08-12T09:19:31.532Z [err] npm
2021-08-12T09:19:31.555Z [err]  WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
2021-08-12T09:19:31.853Z [err] npm
2021-08-12T09:19:31.855Z [err]  WARN 
2021-08-12T09:19:31.856Z [err] deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
2021-08-12T09:19:32.169Z [err] npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
2021-08-12T09:19:32.341Z [err] npm
2021-08-12T09:19:32.362Z [err]  WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
2021-08-12T09:19:32.457Z [err] npm WARN
2021-08-12T09:19:32.460Z [err]  deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
2021-08-12T09:19:32.648Z [err] npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
2021-08-12T09:19:32.736Z [err] npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
2021-08-12T09:20:44.819Z [err] npm WARN deprecated grpc@1.24.11: This library will not receive further updates other than security fixes. We recommend using @grpc/grpc-js instead.
2021-08-12T09:23:52.851Z [err] npm ERR! code 1
2021-08-12T09:23:52.851Z [err] npm ERR! path /config/node-red/node_modules/sqlite3
2021-08-12T09:23:52.899Z [err] npm ERR! command failed
2021-08-12T09:23:52.899Z [err] npm ERR! command sh -c node-pre-gyp install --fallback-to-build
2021-08-12T09:23:52.907Z [err] npm ERR! Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/config/node-red/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/config/node-red/node_modules/sqlite3/lib/binding/node-v83-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
2021-08-12T09:23:52.907Z [err] npm ERR! node-pre-gyp info it worked if it ends with ok
2021-08-12T09:23:52.907Z [err] npm ERR! node-pre-gyp info using node-pre-gyp@1.0.5
2021-08-12T09:23:52.907Z [err] npm ERR! node-pre-gyp info using node@14.17.4 | linux | x64
2021-08-12T09:23:52.907Z [err] npm ERR! node-pre-gyp info check checked for "/config/node-red/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node" (not found)
2021-08-12T09:23:52.907Z [err] npm ERR! node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-linux-x64.tar.gz
2021-08-12T09:23:52.907Z [err] npm ERR! node-pre-gyp ERR! install response status 403 Forbidden on https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-linux-x64.tar.gz 
2021-08-12T09:23:52.907Z [err] npm ERR! node-pre-gyp WARN Pre-built binaries not installable for sqlite3@4.2.0 and node@14.17.4 (node-v83 ABI, musl) (falling back to source compile with node-gyp) 
2021-08-12T09:23:52.907Z [err] npm ERR! node-pre-gyp WARN Hit error response status 403 Forbidden on https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-linux-x64.tar.gz 
2021-08-12T09:23:52.907Z [err] npm ERR! gyp info it worked if it ends with ok
2021-08-12T09:23:52.907Z [err] npm ERR! gyp info using node-gyp@7.1.2
2021-08-12T09:23:52.907Z [err] npm ERR! gyp info using node@14.17.4 | linux | x64
2021-08-12T09:23:52.907Z [err] npm ERR! gyp info ok 
2021-08-12T09:23:52.907Z [err] npm ERR! gyp info it worked if it ends with ok
2021-08-12T09:23:52.907Z [err] npm ERR! gyp info using node-gyp@7.1.2
2021-08-12T09:23:52.907Z [err] npm
2021-08-12T09:23:52.914Z [err]  ERR! gyp info using node@14.17.4 | linux | x64
2021-08-12T09:23:52.914Z [err] npm ERR! gyp info find Python using Python version 3.9.5 found at "/usr/bin/python3"
2021-08-12T09:23:52.914Z [err] npm ERR! gyp info spawn /usr/bin/python3
2021-08-12T09:23:52.914Z [err] npm ERR! gyp info spawn args [
2021-08-12T09:23:52.914Z [err] npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
2021-08-12T09:23:52.914Z [err] npm ERR! gyp info spawn args   'binding.gyp',
2021-08-12T09:23:52.914Z [err] npm ERR! gyp info spawn args   '-f',
2021-08-12T09:23:52.914Z [err] npm ERR! gyp info spawn args   'make',
2021-08-12T09:23:52.914Z [err] npm ERR! gyp info spawn args   '-I',
2021-08-12T09:23:52.914Z [err] npm ERR! gyp info spawn args   '/config/node-red/node_modules/sqlite3/build/config.gypi',
2021-08-12T09:23:52.914Z [err] npm ERR! gyp info spawn args   '-I',
2021-08-12T09:23:52.914Z [err] npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
2021-08-12T09:23:52.914Z [err] npm ERR! gyp info spawn args   '-I',
2021-08-12T09:23:52.914Z [err] npm ERR! gyp info spawn args   '/root/.cache/node-gyp/14.17.4/include/node/common.gypi',
2021-08-12T09:23:52.914Z [err] npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
2021-08-12T09:23:52.914Z [err] npm ERR! gyp info spawn args   '-Dvisibility=default',
2021-08-12T09:23:52.914Z [err] npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/14.17.4',
2021-08-12T09:23:52.914Z [err] npm ERR!
2021-08-12T09:23:52.922Z [err]  gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
2021-08-12T09:23:52.922Z [err] npm
2021-08-12T09:23:52.923Z [err]  ERR!
2021-08-12T09:23:52.924Z [err]  gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/14.17.4/<(target_arch)/node.lib',
2021-08-12T09:23:52.924Z [err] npm 
2021-08-12T09:23:52.929Z [err] ERR!
2021-08-12T09:23:52.933Z [err]  gyp info spawn args   '-Dmodule_root_dir=/config/node-red/node_modules/sqlite3',
2021-08-12T09:23:52.933Z [err] npm 
2021-08-12T09:23:52.934Z [err] ERR! gyp info spawn args   '-Dnode_engine=v8',
2021-08-12T09:23:52.934Z [err] npm ERR! gyp info spawn args   '--depth=.',
2021-08-12T09:23:52.934Z [err] npm
2021-08-12T09:23:52.936Z [err]  ERR! gyp info spawn args   '--no-parallel',
2021-08-12T09:23:52.936Z [err] npm ERR! gyp info spawn args   '--generator-output',
2021-08-12T09:23:52.936Z [err] npm 
2021-08-12T09:23:52.940Z [err] ERR! gyp info spawn args   'build',
2021-08-12T09:23:52.940Z [err] npm ERR! gyp info spawn args   '-Goutput_dir=.'
2021-08-12T09:23:52.940Z [err] npm ERR!
2021-08-12T09:23:52.941Z [err]  gyp info spawn args ]
2021-08-12T09:23:52.941Z [err] npm ERR! gyp info ok 
2021-08-12T09:23:52.957Z [err] npm 
2021-08-12T09:23:52.982Z [err] ERR! gyp info it worked if it ends with ok
2021-08-12T09:23:52.982Z [err] npm ERR! gyp info using node-gyp@7.1.2
2021-08-12T09:23:52.982Z [err] npm ERR! gyp info using node@14.17.4 | linux | x64
2021-08-12T09:23:52.982Z [err] npm ERR! gyp ERR! build error 
2021-08-12T09:23:52.982Z [err] npm ERR! gyp ERR! stack Error: not found: make
2021-08-12T09:23:52.982Z [err] npm ERR! gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:10:17)
2021-08-12T09:23:52.982Z [err] npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:57:18
2021-08-12T09:23:52.982Z [err] npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
2021-08-12T09:23:52.982Z [err] npm ERR! gyp ERR! stack     at step (/usr/lib/node_modules/npm/node_modules/which/which.js:54:21)
2021-08-12T09:23:52.982Z [err] npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:71:22
2021-08-12T09:23:52.982Z [err] npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
2021-08-12T09:23:52.982Z [err] npm ERR! gyp ERR! stack     at subStep (/usr/lib/node_modules/npm/node_modules/which/which.js:69:33)
2021-08-12T09:23:52.982Z [err] npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:80:22
2021-08-12T09:23:52.982Z [err] npm 
2021-08-12T09:23:52.991Z [err] ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2021-08-12T09:23:52.991Z [err] npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2021-08-12T09:23:52.991Z [err] npm ERR! gyp ERR! System Linux 5.10.53
2021-08-12T09:23:52.991Z [err] npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/config/node-red/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/config/node-red/node_modules/sqlite3/lib/binding/node-v83-linux-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
2021-08-12T09:23:52.991Z [err] npm ERR! gyp ERR! cwd /config/node-red/node_modules/sqlite3
2021-08-12T09:23:52.991Z [err] npm ERR! gyp ERR! node -v v14.17.4
2021-08-12T09:23:52.991Z [err] npm ERR! gyp ERR! node-gyp -v v7.1.2
2021-08-12T09:23:52.991Z [err] npm ERR! gyp ERR! not ok 
2021-08-12T09:23:52.991Z [err] npm ERR! node-pre-gyp ERR! build error 
2021-08-12T09:23:52.991Z [err] npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/config/node-red/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/config/node-red/node_modules/sqlite3/lib/binding/node-v83-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
2021-08-12T09:23:52.991Z [err] npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/config/node-red/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
2021-08-12T09:23:52.991Z [err] npm ERR!
2021-08-12T09:23:52.995Z [err]  node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
2021-08-12T09:23:52.995Z [err] npm ERR! node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
2021-08-12T09:23:52.995Z [err] npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
2021-08-12T09:23:52.995Z [err] npm 
2021-08-12T09:23:53.006Z [err] ERR! node-pre-gyp ERR! System Linux 5.10.53
2021-08-12T09:23:53.006Z [err] npm ERR! node-pre-gyp ERR! command "/usr/bin/node" "/config/node-red/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
2021-08-12T09:23:53.006Z [err] npm ERR! node-pre-gyp ERR! cwd /config/node-red/node_modules/sqlite3
2021-08-12T09:23:53.006Z [err] npm ERR! node-pre-gyp ERR! node -v v14.17.4
2021-08-12T09:23:53.006Z [err] npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.5
2021-08-12T09:23:53.006Z [err] npm ERR! node-pre-gyp ERR! not ok
2021-08-12T09:23:53.569Z [err] 
2021-08-12T09:23:53.579Z [err] npm ERR! A complete log of this run can be found in:
2021-08-12T09:23:53.579Z [err] npm ERR!     /root/.npm/_logs/2021-08-12T09_23_53_291Z-debug.log
2021-08-12T09:23:53.719Z rc=1

**Comment by shadyshrif** [comment]
Your node js version is 14 while sqlite3 supports only until node version 13
Downgrade your node version to 13.x
https://stackoverflow.com/questions/47008159/how-to-downgrade-node-version

**Comment by guidone** [comment]
👍
