### ISSUE TITLE
MC not working in Docker

### ISSUE THREAD

**Issue by Iciir** [guidone/node-red-contrib-chatbot#622]
I tried setting up a fresh docker container with Node-RED and REDBot, and enable Mission Control with the environment variable:

REDBOT_ENABLE_MISSION_CONTROL=true

```
Welcome to Node-RED
===================
25 Nov 04:07:42 - [info] Node-RED version: v3.1.0
25 Nov 04:07:42 - [info] Node.js  version: v16.20.2
25 Nov 04:07:42 - [info] Linux 5.15.74-1-lts x64 LE
25 Nov 04:07:43 - [info] Loading palette nodes
25 Nov 04:07:45 - [info] RedBot version: 1.2.4 (node-red-contrib-chatbot)
25 Nov 04:07:46 - [info] Red Bot Mission Control configuration:
25 Nov 04:07:46 - [info]   admin root: /
25 Nov 04:07:46 - [info]   backend environment: development
25 Nov 04:07:46 - [info]   front end environment: production
25 Nov 04:07:46 - [info]   salt: default
25 Nov 04:07:46 - [info]   dbPath: /data/mission-control.sqlite
25 Nov 04:07:49 - [red] Uncaught Exception:
25 Nov 04:07:49 - [error] Error: Please install sqlite3 package manually
    at ConnectionManager._loadDialectModule (/data/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:88:15)
    at new ConnectionManager (/data/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:22:21)
    at new SqliteDialect (/data/node_modules/sequelize/lib/dialects/sqlite/index.js:14:30)
    at new Sequelize (/data/node_modules/sequelize/lib/sequelize.js:334:20)
    at module.exports (/data/node_modules/node-red-contrib-chatbot/lib/authentication/index.js:10:21)
    at bootstrap (/data/node_modules/node-red-contrib-chatbot/nodes/mc.js:151:83)
    at module.exports (/data/node_modules/node-red-contrib-chatbot/nodes/mc.js:454:5)
    at module.exports (/data/node_modules/node-red-contrib-chatbot/nodes/mc-base.js:2:18)
    at loadNodeSet (/usr/src/node-red/node_modules/@node-red/registry/lib/loader.js:353:27)
    at /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js:447:31
    at Array.forEach (<anonymous>)
    at loadNodeSetList (/usr/src/node-red/node_modules/@node-red/registry/lib/loader.js:442:11)
    at /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js:145:16
```

The `/data` folder is bound to a local folder as necessary, no other changes to the default container.

I also tried

```
module.exports = {
	// ...
  // Node-RED configuration
  // ...
  RedBot: {
    enableMissionControl: true
  }
};
```

—  with the same result.

Trying to `npm install sqlite3`, says:

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: graphql-relay@0.10.0
npm WARN Found: graphql@14.7.0
npm WARN node_modules/graphql
npm WARN   peer graphql@"^14.2.1 || ^15.0.0 || ^16.0.0" from @apollographql/apollo-tools@0.5.4
npm WARN   node_modules/@apollographql/apollo-tools
npm WARN     @apollographql/apollo-tools@"^0.5.0" from apollo-server-core@2.26.2
npm WARN     node_modules/apollo-server-core
npm WARN     1 more (graphql-extensions)
npm WARN   25 more (@apollographql/graphql-upload-8-fork, apollo-boost, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer graphql@"^16.2.0" from graphql-relay@0.10.0
npm WARN node_modules/graphql-relay
npm WARN   peer graphql-relay@"^0.4.2 || ^0.5.0 || ^0.7.0 || ^0.8.0 || ^0.9.0 || ^0.10.0" from graphql-sequelize@9.5.1
npm WARN   node_modules/graphql-sequelize
npm WARN 
npm WARN Conflicting peer dependency: graphql@16.8.1
npm WARN node_modules/graphql
npm WARN   peer graphql@"^16.2.0" from graphql-relay@0.10.0
npm WARN   node_modules/graphql-relay
npm WARN     peer graphql-relay@"^0.4.2 || ^0.5.0 || ^0.7.0 || ^0.8.0 || ^0.9.0 || ^0.10.0" from graphql-sequelize@9.5.1
npm WARN     node_modules/graphql-sequelize
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@slack/logger@4.0.0',
npm WARN EBADENGINE   required: { node: '>= 18', npm: '>= 8.6.0' },
npm WARN EBADENGINE   current: { node: 'v16.14.0', npm: '9.2.0' }
npm WARN EBADENGINE }
```

**Comment by MrSiO** [comment]
Same issue here.
Any updates on how to fix this and be able to install from 'manage palette' ?
