### ISSUE TITLE
npm error: Invalid name: "@slack/client"

### ISSUE THREAD

**Issue by LennartHennigs** [guidone/node-red-contrib-chatbot#81]
Hi,
when I try to install the package (on a mac) I get the following error:

```
npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-red-contrib-chatbot"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2

npm ERR! Invalid name: "@slack/client"
```

The log file says the following:

```
1050 verbose stack Error: Invalid name: "@slack/client"
1050 verbose stack     at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:297:15)
1050 verbose stack     at Object.fixNameField (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:201:5)
1050 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:38
1050 verbose stack     at Array.forEach (native)
1050 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:28:15)
1050 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:349:5)
1050 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
1050 verbose stack     at ReadFileContext.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:189:20)
1050 verbose stack     at ReadFileContext.callback (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
``` 

Any suggestion?
Cheers.

**Comment by guidone** [comment]
I tried right now and it works, I generally use [NP](https://github.com/sindresorhus/np) to publish the package, it removes all packages and download them all again before publishing the package.
Which version of npm do you have?
If you try to install the module "@slack/client" separately what do you get?

**Comment by LennartHennigs** [comment]
Hey,
I updated npm (from 4.1.2 to 5.0.3) and now the install worked fine.
Thanks for the hint and prompt reply.

Cheers.
