### ISSUE TITLE
timeout issue and socket issue

### ISSUE THREAD

**Issue by jmikerq** [guidone/node-red-contrib-chatbot#9]
`Unhandled rejection RequestError: Error: connect ETIMEDOUT 149.154.167.200:443
    at new RequestError (/vagrant/stand-alone-node-red/node_modules/node-red/node_modules/node-red-contrib-chatbot/node_modules/node-telegram-bot-api/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/vagrant/stand-alone-node-red/node_modules/node-red/node_modules/node-red-contrib-chatbot/node_modules/node-telegram-bot-api/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/vagrant/stand-alone-node-red/node_modules/node-red/node_modules/node-red-contrib-chatbot/node_modules/request/request.js:187:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/vagrant/stand-alone-node-red/node_modules/node-red/node_modules/node-red-contrib-chatbot/node_modules/request/request.js:813:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:267:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at emitErrorNT (net.js:1269:8)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)`

`Unhandled rejection RequestError: Error: socket hang up
    at new RequestError (/vagrant/stand-alone-node-red/node_modules/node-red/node_modules/node-red-contrib-chatbot/node_modules/node-telegram-bot-api/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/vagrant/stand-alone-node-red/node_modules/node-red/node_modules/node-red-contrib-chatbot/node_modules/node-telegram-bot-api/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/vagrant/stand-alone-node-red/node_modules/node-red/node_modules/node-red-contrib-chatbot/node_modules/request/request.js:187:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/vagrant/stand-alone-node-red/node_modules/node-red/node_modules/node-red-contrib-chatbot/node_modules/request/request.js:813:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:267:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at emitErrorNT (net.js:1269:8)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)`

When I leave the nodes for a while(not doing anything), I keep receiving these unhandled error msgs. They are not crashing node-red, but it is kind of annoying.

**Comment by guidone** [comment]
I agree is annoying.
It's an untrapped exception of the telegram bot api module. There are some commits for that library that fix the problem but are not yet published, I think it's a matter of days
